// Generates data/hexmap.json from data/mapspec.json.
// Each territory has a `seeds` skeleton (one or more hexes sketching its shape)
// and a `size` (relative area). A hex is assigned to the territory whose nearest
// skeleton point is closest in weighted distance (dist / sqrt(size)); hexes
// beyond reach R of every skeleton are ocean. Filling completely means internal
// borders touch; elongated skeletons give elongated countries.
// Tune reach with:  node tools/gen-map.mjs [R]
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { hexToPixel } from '../src/hex.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const spec = JSON.parse(readFileSync(join(root, 'data/mapspec.json'), 'utf8'));
const R = Number(process.argv[2] ?? 3.1);

const ids = Object.keys(spec).filter(k => !k.startsWith('_') && k !== 'base');
const skel = {}, w = {};
for (const id of ids) {
  const pts = spec[id].seeds || [spec[id].seed];
  skel[id] = pts.map(([c, r]) => hexToPixel(c, r, 1));
  w[id] = Math.sqrt(spec[id].size);
}

const allPts = ids.flatMap(id => spec[id].seeds || [spec[id].seed]);
const cols = allPts.map(p => p[0]), rows = allPts.map(p => p[1]);
const c0 = Math.min(...cols) - 7, c1 = Math.max(...cols) + 7;
const r0 = Math.min(...rows) - 7, r1 = Math.max(...rows) + 7;

const territories = {}; for (const id of ids) territories[id] = [];
let placed = 0;
for (let r = r0; r <= r1; r++) {
  for (let c = c0; c <= c1; c++) {
    const p = hexToPixel(c, r, 1);
    let best = null, bestD = Infinity;
    for (const id of ids) {
      let dmin = Infinity;
      for (const s of skel[id]) { const d = Math.hypot(p.x - s.x, p.y - s.y); if (d < dmin) dmin = d; }
      dmin /= w[id];
      if (dmin < bestD) { bestD = dmin; best = id; }
    }
    if (best && bestD <= R) { territories[best].push([c, r]); placed++; }
  }
}

const out = { _comment: 'GENERATED by tools/gen-map.mjs from data/mapspec.json. Edit mapspec, not this.', layout: 'odd-r', orientation: 'pointy', territories };
writeFileSync(join(root, 'data/hexmap.json'),
  JSON.stringify(out).replace(/,"(\w[\w_]*":\[)/g, ',\n    "$1').replace(/{"_comment/, '{\n  "_comment') + '\n');

const cnt = ids.map(id => [id, territories[id].length]).sort((a, b) => a[1] - b[1]);
console.log(`R=${R}  placed ${placed} hexes`);
console.log('smallest:', cnt.slice(0, 4).map(x => `${x[0]} ${x[1]}`).join(', '));
console.log('largest: ', cnt.slice(-4).map(x => `${x[0]} ${x[1]}`).join(', '));
console.log('-> data/hexmap.json (run `npm run validate`)');
