// Generates data/hexmap.json from data/mapspec.json using weighted-Voronoi fill:
// every hex within reach of a seed is assigned to the nearest seed (weighted by
// sqrt(size), so larger countries claim more area). Filling completely means all
// internal borders touch; "reach" (R) leaves ocean between continents and around
// islands. Tune R via:  node tools/gen-map.mjs [R]
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { hexToPixel } from '../src/hex.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const spec = JSON.parse(readFileSync(join(root, 'data/mapspec.json'), 'utf8'));
const base = spec.base ?? 10;
const R = Number(process.argv[2] ?? 4.6);   // reach in (weighted) pixel units

const ids = Object.keys(spec).filter(k => !k.startsWith('_') && k !== 'base');
const seedPix = {}, w = {};
for (const id of ids) {
  const [sc, sr] = spec[id].seed;
  seedPix[id] = hexToPixel(sc, sr, 1);
  w[id] = Math.sqrt(spec[id].size);   // multiplicative weight: cell area ~ size
}

// Bounding box over all seeds, padded, scanned hex by hex.
const cols = ids.map(id => spec[id].seed[0]), rows = ids.map(id => spec[id].seed[1]);
const c0 = Math.min(...cols) - 6, c1 = Math.max(...cols) + 6;
const r0 = Math.min(...rows) - 6, r1 = Math.max(...rows) + 6;

const territories = {}; for (const id of ids) territories[id] = [];
let placed = 0;
for (let r = r0; r <= r1; r++) {
  for (let c = c0; c <= c1; c++) {
    const p = hexToPixel(c, r, 1);
    let best = null, bestD = Infinity;
    for (const id of ids) {
      const s = seedPix[id];
      const d = Math.hypot(p.x - s.x, p.y - s.y) / w[id];   // weighted distance
      if (d < bestD) { bestD = d; best = id; }
    }
    if (best && bestD <= R) { territories[best].push([c, r]); placed++; }
  }
}

const out = { _comment: 'GENERATED by tools/gen-map.mjs from data/mapspec.json. Edit mapspec, not this.', layout: 'odd-r', orientation: 'pointy', territories };
writeFileSync(join(root, 'data/hexmap.json'),
  JSON.stringify(out).replace(/,"(\w[\w_]*":\[)/g, ',\n    "$1').replace(/{"_comment/, '{\n  "_comment') + '\n');

const sizes = ids.map(id => `${id.slice(0,4)}:${territories[id].length}`);
console.log(`R=${R}  placed ${placed} hexes`);
console.log('sizes:', sizes.join(' '));
console.log('-> data/hexmap.json (run `npm run validate`)');
